# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amazon/suez/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter suez,$(TARGET_DEVICE)),)

# vendor/amazon/suez/proprietary/framework/android.amazon.perm/android.amazon.perm.apk \

# LOCAL_PREBUILT_JAVA_LIBRARIES := \
#     vendor/amazon/suez/proprietary/framework/amazon-ads-registration.jar \
#     vendor/amazon/suez/proprietary/framework/amazon-remoteviews.jar \
#     vendor/amazon/suez/proprietary/framework/amazoncardlib.jar \
#     vendor/amazon/suez/proprietary/framework/android-icu4j.jar \
#     vendor/amazon/suez/proprietary/framework/aspclient.jar \
#     vendor/amazon/suez/proprietary/framework/AWSRemoteConfigurationAndroidClient.jar \
#     vendor/amazon/suez/proprietary/framework/com.amazon.device.home.jar \
#     vendor/amazon/suez/proprietary/framework/com.amazon.device.print.jar \
#     vendor/amazon/suez/proprietary/framework/com.amazon.device.search.jar \
#     vendor/amazon/suez/proprietary/framework/com.amazon.h2contracts.jar \
#     vendor/amazon/suez/proprietary/framework/com.amazon.h2shared.jar \
#     vendor/amazon/suez/proprietary/framework/com.amazon.identity.auth.device.jar \
#     vendor/amazon/suez/proprietary/framework/com.amazon.kindle.cms.jar \
#     vendor/amazon/suez/proprietary/framework/com.amazon.readynow.api.jar \
#     vendor/amazon/suez/proprietary/framework/com.amazon.sharingservice.android.client.core.lib.jar \
#     vendor/amazon/suez/proprietary/framework/com.amazon.sharingservice.android.client.jar \
#     vendor/amazon/suez/proprietary/framework/com.amazon.sics.jar \
#     vendor/amazon/suez/proprietary/framework/com.amazon.sync.api.jar \
#     vendor/amazon/suez/proprietary/framework/com.google.widevine.software.drm.jar \
#     vendor/amazon/suez/proprietary/framework/dolby_ds.jar \
#     vendor/amazon/suez/proprietary/framework/dolby_ds2.jar \
#     vendor/amazon/suez/proprietary/framework/EnhancedCameraAPI.jar \
#     vendor/amazon/suez/proprietary/framework/fireos-res/fireos-res.apk \
#     vendor/amazon/suez/proprietary/framework/fosframework.jar \
#     vendor/amazon/suez/proprietary/framework/fosinit.jar \
#     vendor/amazon/suez/proprietary/framework/fosservices.jar \
#     vendor/amazon/suez/proprietary/framework/i18n-utilities.jar \
#     vendor/amazon/suez/proprietary/framework/icu4j.jar \
#     vendor/amazon/suez/proprietary/framework/langpackage-client.jar \
#     vendor/amazon/suez/proprietary/framework/mediatek-framework.jar \
#     vendor/amazon/suez/proprietary/framework/MozartClientAPI.jar \
#     vendor/amazon/suez/proprietary/framework/precog-api.jar \
#     vendor/amazon/suez/proprietary/framework/retaildemoapi.jar \
#     vendor/amazon/suez/proprietary/framework/rtmpclient.jar \
#     vendor/amazon/suez/proprietary/framework/tahoe.alexa.client.jar \
#     vendor/amazon/suez/proprietary/framework/webviewext.jar \

endif
